# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RemoteAPI.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='RemoteAPI.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\n\005Proto',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fRemoteAPI.proto\"\x1d\n\x05Vec2D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\"(\n\x05Vec3D\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\"c\n\x0eRemoteGeometry\x12\x14\n\x0c\x66ield_length\x18\x01 \x01(\x05\x12\x13\n\x0b\x66ield_width\x18\x02 \x01(\x05\x12\x12\n\ngoal_width\x18\x03 \x01(\x05\x12\x12\n\ngoal_depth\x18\x04 \x01(\x05\"\x96\x01\n\x08\x43ommands\x12 \n\x18\x65nable_ball_auto_capture\x18\x01 \x01(\x08\x12\x0c\n\x04mode\x18\x02 \x01(\x05\x12\x16\n\x0eis_world_frame\x18\x03 \x01(\x08\x12 \n\x10motion_set_point\x18\x04 \x01(\x0b\x32\x06.Vec3D\x12 \n\x10kicker_set_point\x18\x05 \x01(\x0b\x32\x06.Vec3D\"q\n\x11RobotInternalData\x12\x19\n\ttrans_vel\x18\x01 \x01(\x0b\x32\x06.Vec2D\x12\x1a\n\ntrans_disp\x18\x02 \x01(\x0b\x32\x06.Vec2D\x12\x11\n\trotat_vel\x18\x03 \x01(\x01\x12\x12\n\nrotat_disp\x18\x04 \x01(\x01\"\x98\x01\n\nVisionData\x12\x17\n\x07\x62ot_pos\x18\x01 \x01(\x0b\x32\x06.Vec2D\x12\x17\n\x07\x62ot_vel\x18\x02 \x01(\x0b\x32\x06.Vec2D\x12\x0f\n\x07\x62ot_ang\x18\x03 \x01(\x01\x12\x13\n\x0b\x62ot_ang_vel\x18\x04 \x01(\x01\x12\x18\n\x08\x62\x61ll_pos\x18\x05 \x01(\x0b\x32\x06.Vec2D\x12\x18\n\x08\x62\x61ll_vel\x18\x06 \x01(\x0b\x32\x06.Vec2DB\x07\n\x05Protob\x06proto3'
)




_VEC2D = _descriptor.Descriptor(
  name='Vec2D',
  full_name='Vec2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec2D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec2D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=48,
)


_VEC3D = _descriptor.Descriptor(
  name='Vec3D',
  full_name='Vec3D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec3D.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec3D.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='Vec3D.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=50,
  serialized_end=90,
)


_REMOTEGEOMETRY = _descriptor.Descriptor(
  name='RemoteGeometry',
  full_name='RemoteGeometry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='field_length', full_name='RemoteGeometry.field_length', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='field_width', full_name='RemoteGeometry.field_width', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goal_width', full_name='RemoteGeometry.goal_width', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='goal_depth', full_name='RemoteGeometry.goal_depth', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=92,
  serialized_end=191,
)


_COMMANDS = _descriptor.Descriptor(
  name='Commands',
  full_name='Commands',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='enable_ball_auto_capture', full_name='Commands.enable_ball_auto_capture', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='Commands.mode', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_world_frame', full_name='Commands.is_world_frame', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='motion_set_point', full_name='Commands.motion_set_point', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='kicker_set_point', full_name='Commands.kicker_set_point', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=194,
  serialized_end=344,
)


_ROBOTINTERNALDATA = _descriptor.Descriptor(
  name='RobotInternalData',
  full_name='RobotInternalData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='trans_vel', full_name='RobotInternalData.trans_vel', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='trans_disp', full_name='RobotInternalData.trans_disp', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotat_vel', full_name='RobotInternalData.rotat_vel', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='rotat_disp', full_name='RobotInternalData.rotat_disp', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=346,
  serialized_end=459,
)


_VISIONDATA = _descriptor.Descriptor(
  name='VisionData',
  full_name='VisionData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bot_pos', full_name='VisionData.bot_pos', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bot_vel', full_name='VisionData.bot_vel', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bot_ang', full_name='VisionData.bot_ang', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='bot_ang_vel', full_name='VisionData.bot_ang_vel', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball_pos', full_name='VisionData.ball_pos', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball_vel', full_name='VisionData.ball_vel', index=5,
      number=6, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=614,
)

_COMMANDS.fields_by_name['motion_set_point'].message_type = _VEC3D
_COMMANDS.fields_by_name['kicker_set_point'].message_type = _VEC3D
_ROBOTINTERNALDATA.fields_by_name['trans_vel'].message_type = _VEC2D
_ROBOTINTERNALDATA.fields_by_name['trans_disp'].message_type = _VEC2D
_VISIONDATA.fields_by_name['bot_pos'].message_type = _VEC2D
_VISIONDATA.fields_by_name['bot_vel'].message_type = _VEC2D
_VISIONDATA.fields_by_name['ball_pos'].message_type = _VEC2D
_VISIONDATA.fields_by_name['ball_vel'].message_type = _VEC2D
DESCRIPTOR.message_types_by_name['Vec2D'] = _VEC2D
DESCRIPTOR.message_types_by_name['Vec3D'] = _VEC3D
DESCRIPTOR.message_types_by_name['RemoteGeometry'] = _REMOTEGEOMETRY
DESCRIPTOR.message_types_by_name['Commands'] = _COMMANDS
DESCRIPTOR.message_types_by_name['RobotInternalData'] = _ROBOTINTERNALDATA
DESCRIPTOR.message_types_by_name['VisionData'] = _VISIONDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Vec2D = _reflection.GeneratedProtocolMessageType('Vec2D', (_message.Message,), {
  'DESCRIPTOR' : _VEC2D,
  '__module__' : 'RemoteAPI_pb2'
  # @@protoc_insertion_point(class_scope:Vec2D)
  })
_sym_db.RegisterMessage(Vec2D)

Vec3D = _reflection.GeneratedProtocolMessageType('Vec3D', (_message.Message,), {
  'DESCRIPTOR' : _VEC3D,
  '__module__' : 'RemoteAPI_pb2'
  # @@protoc_insertion_point(class_scope:Vec3D)
  })
_sym_db.RegisterMessage(Vec3D)

RemoteGeometry = _reflection.GeneratedProtocolMessageType('RemoteGeometry', (_message.Message,), {
  'DESCRIPTOR' : _REMOTEGEOMETRY,
  '__module__' : 'RemoteAPI_pb2'
  # @@protoc_insertion_point(class_scope:RemoteGeometry)
  })
_sym_db.RegisterMessage(RemoteGeometry)

Commands = _reflection.GeneratedProtocolMessageType('Commands', (_message.Message,), {
  'DESCRIPTOR' : _COMMANDS,
  '__module__' : 'RemoteAPI_pb2'
  # @@protoc_insertion_point(class_scope:Commands)
  })
_sym_db.RegisterMessage(Commands)

RobotInternalData = _reflection.GeneratedProtocolMessageType('RobotInternalData', (_message.Message,), {
  'DESCRIPTOR' : _ROBOTINTERNALDATA,
  '__module__' : 'RemoteAPI_pb2'
  # @@protoc_insertion_point(class_scope:RobotInternalData)
  })
_sym_db.RegisterMessage(RobotInternalData)

VisionData = _reflection.GeneratedProtocolMessageType('VisionData', (_message.Message,), {
  'DESCRIPTOR' : _VISIONDATA,
  '__module__' : 'RemoteAPI_pb2'
  # @@protoc_insertion_point(class_scope:VisionData)
  })
_sym_db.RegisterMessage(VisionData)


DESCRIPTOR._options = None
# @@protoc_insertion_point(module_scope)
